# Build this image with: docker build -f Dockerfile.rbuilder -t rbuilder-caner:latest .

FROM ghcr.io/flashbots/rbuilder:sha-51e6940 AS base

FROM ubuntu:24.04

ARG RBUILDER_BIN
WORKDIR /app
COPY --from=base --chmod=0755 /app/rbuilder /app/rbuilder
ENTRYPOINT [ "/app/rbuilder" ]
