#!/usr/bin/env bash
# Register the VM builder with the BuilderHub

set -eu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "register-builder.sh: Running builder registration..."

# Get builder IP from environment or default to 10.0.2.2
HOST_IP=${HOST_IP:-10.0.2.2}

# Default values for the registration
BUILDER_ID="playground_vm_builder"
MEASUREMENT_ID="test1"
NETWORK="playground"
BUILDER_IP="1.2.3.4"

# Read genesis.json generated by the recipe
GENESIS_JSON=$(<"$HOME/.local/state/builder-playground/devnet/genesis.json")

# path to the embedded default (adjust if the file lives elsewhere)
CONFIG_YAML="$SCRIPT_DIR/../config/builderhub-config.yaml"

# Convert YAML to JSON and inject genesis
CONFIG_JSON=$(yq eval -o=json "$CONFIG_YAML") || {
    echo "register-builder.sh: Error - invalid YAML in $CONFIG_YAML" >&2
    exit 1
}
# Replace the genesis field with the actual genesis JSON
CONFIG_JSON=$(echo "$CONFIG_JSON" | jq --argjson genesis "$GENESIS_JSON" '.genesis = $genesis')

# Function to extract port from manifest
# Usage: extract_port_from_manifest <service_name> <port_name>
extract_port_from_manifest() {
    local service_name="$1"
    local port_name="$2"
    local manifest_file="${MANIFEST_PATH:-$HOME/.local/state/builder-playground/devnet/manifest.json}"

    # Check if manifest file exists
    if [[ ! -f "$manifest_file" ]]; then
        echo "register-builder.sh: Error - manifest file not found at $manifest_file" >&2
        exit 1
    fi

    # Extract port using jq
    local port
    port=$(jq -r --arg service "$service_name" --arg port "$port_name" \
        '.services[] | select(.name == $service) | .ports[] | select(.name == $port) | .port' \
        "$manifest_file" 2>/dev/null || echo "null")

    # Validate port value
    if [[ "$port" = "null" || -z "$port" ]]; then
        echo "register-builder.sh: Error - port $port_name not found for service $service_name" >&2
        exit 1
    fi

    echo "$port"
}

# Get ports from manifest dynamically
echo "register-builder.sh: Reading ports from manifest..."

# Use known port names for services - these are consistent across deployments
# builder-hub-api uses 'admin' port for admin API
BUILDER_ADMIN_API_PORT=$(extract_port_from_manifest "builder-hub-api" "admin")
echo "register-builder.sh: BUILDER_ADMIN_API_PORT = $BUILDER_ADMIN_API_PORT"

# beacon service - use 'http' port for beacon API calls
BEACON_API_PORT=$(extract_port_from_manifest "beacon" "http")
echo "register-builder.sh: BEACON_API_PORT = $BEACON_API_PORT"

# el service - use 'http' port for JSON-RPC calls
RETH_API_PORT=$(extract_port_from_manifest "el" "http")
echo "register-builder.sh: RETH_API_PORT = $RETH_API_PORT"

# Get the beacon node identity
echo "register-builder.sh: Getting beacon node identity..."
BEACON_IDENTITY_URL="http://localhost:${BEACON_API_PORT}/eth/v1/node/identity"
IDENTITY_RESPONSE=$(curl -sf "$BEACON_IDENTITY_URL") || {
    echo "register-builder.sh: Error getting beacon node identity"
    exit 1
}

# Extract peer ID from the identity response
PEER_ID=$(echo "$IDENTITY_RESPONSE" | jq -r '.data.peer_id') || {
    echo "register-builder.sh: Error extracting peer ID from beacon node identity"
    exit 1
}
if [ "$PEER_ID" = "null" ] || [ -z "$PEER_ID" ]; then
    echo "register-builder.sh: Error extracting peer ID from beacon node identity"
    exit 1
fi

# Construct libp2p address with the known host IP
LIBP2P_ADDR="/ip4/${HOST_IP}/tcp/9001/p2p/${PEER_ID}"
echo "register-builder.sh: Setting builder config var libp2p-addr: ${LIBP2P_ADDR}"

# Get reth node info to extract enode
echo "register-builder.sh: Getting reth node info..."
RETH_NODE_INFO_URL="http://localhost:${RETH_API_PORT}/"
RETH_RESPONSE=$(curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"admin_nodeInfo","id":1}' \
    "$RETH_NODE_INFO_URL") || {
    echo "register-builder.sh: Error getting reth node info"
    exit 1
}

# Extract enode from response
ENODE=$(echo "$RETH_RESPONSE" | jq -r '.result.enode') || {
    echo "register-builder.sh: Error extracting enode from reth node info"
    exit 1
}
if [ "$ENODE" = "null" ] || [ -z "$ENODE" ]; then
    echo "register-builder.sh: Error extracting enode from reth node info"
    exit 1
fi

# Replace the IP address in the enode with the host IP
BOOT_NODE=$(echo "$ENODE" | sed "s|@[^:]*:|@${HOST_IP}:|")
echo "register-builder.sh: Setting builder config var bootnode: ${BOOT_NODE}"

# Replace template variables in the JSON config
CONFIG="$CONFIG_JSON"
CONFIG=$(echo "$CONFIG" | sed "s|{{EL_BOOTNODE}}|${BOOT_NODE}|g")
CONFIG=$(echo "$CONFIG" | sed "s|{{CL_LIBP2P_ADDR}}|${LIBP2P_ADDR}|g")

echo "register-builder.sh: Registering builder with BuilderHub..."

# Create Allow-All Measurements
echo "register-builder.sh: Creating measurements..."
curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d "{\"measurement_id\":\"$MEASUREMENT_ID\",\"attestation_type\":\"test\",\"measurements\":{}}" \
    "http://localhost:${BUILDER_ADMIN_API_PORT}/api/admin/v1/measurements" || {
    echo "register-builder.sh: Error creating measurements"
    exit 1
}

# Enable Measurements
echo "register-builder.sh: Enabling measurements..."
curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d "{\"enabled\":true}" \
    "http://localhost:${BUILDER_ADMIN_API_PORT}/api/admin/v1/measurements/activation/$MEASUREMENT_ID" || {
    echo "register-builder.sh: Error enabling measurements"
    exit 1
}

# Create the builder
echo "register-builder.sh: Creating builder..."
curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"$BUILDER_ID\",\"ip_address\":\"$BUILDER_IP\",\"network\":\"$NETWORK\"}" \
    "http://localhost:${BUILDER_ADMIN_API_PORT}/api/admin/v1/builders" || {
    echo "register-builder.sh: Error creating builder"
    exit 1
}

# Create Builder Configuration
echo "register-builder.sh: Setting builder configuration..."
curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d "$CONFIG" \
    "http://localhost:${BUILDER_ADMIN_API_PORT}/api/admin/v1/builders/configuration/$BUILDER_ID" || {
    echo "register-builder.sh: Error setting builder configuration"
    exit 1
}

# Create Builder Secrets (using same config for secrets in this case)
echo "register-builder.sh: Setting builder secrets..."
curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d "$CONFIG" \
    "http://localhost:${BUILDER_ADMIN_API_PORT}/api/admin/v1/builders/secrets/$BUILDER_ID" || {
    echo "register-builder.sh: Error setting builder secrets"
    exit 1
}

# Enable Builder
echo "register-builder.sh: Enabling builder..."
curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d "{\"enabled\":true}" \
    "http://localhost:${BUILDER_ADMIN_API_PORT}/api/admin/v1/builders/activation/$BUILDER_ID" || {
    echo "register-builder.sh: Error enabling builder"
    exit 1
}

echo "register-builder.sh: Builder registration completed successfully!"
