package playground

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/ethereum/go-ethereum/core"
	"github.com/stretchr/testify/require"
)

func TestEnodeGeneration(t *testing.T) {
	// Test that the enodes generated by output are deterministic
	o1 := newTestOutput(t)
	o2 := newTestOutput(t)

	for i := 0; i < 10; i++ {
		if o1.GetEnodeAddr().NodeID() != o2.GetEnodeAddr().NodeID() {
			t.Fatalf("enode IDs are not the same")
		}
	}
}

func TestL2PrefundedAccounts(t *testing.T) {
	o := newTestOutput(t)

	b := NewArtifactsBuilder()
	b.WithL2()
	require.NoError(t, b.Build(o))

	genesisRaw, err := o.Read("l2-genesis.json")
	require.NoError(t, err)

	var genesis core.Genesis
	require.NoError(t, json.Unmarshal([]byte(genesisRaw), &genesis))
	require.Len(t, genesis.Alloc, 10)
}

func newTestOutput(t *testing.T) *output {
	dir, err := os.MkdirTemp("/tmp", "test-output")
	if err != nil {
		t.Fatalf("failed to create temporal folder: %v", err)
	}
	defer os.RemoveAll(dir)

	o := &output{
		dst: dir,
	}
	return o
}
